name: Create Issues

on:
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  create-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run issue creation script
        env:
          SECRET_ID: ${{ secrets.SECRET_ID }}
          OWNER: "deadaf54"
          REPO: "MiCode/Xiaomi_Kernel_OpenSource"
          TITLE: "Release Redmi note 9 (Merlin) , Redmi 9 (Lancelot) and Poco M2 (Shiva) S Kernel Source "
          BODY: "It's been almost a year since the release of MIUI S for the following devices, but Xiaomi (violating GPL license) still hasn't released the S kernel source code"
          NUM_ISSUES: 1000
        run: |
          for i in $(seq 1 $NUM_ISSUES)
          do
            curl -X POST \
              -H "Authorization: token $SECRET_ID" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/$OWNER/$REPO/issues \
              -d "{\"title\":\"$TITLE\",\"body\":\"$BODY\"}"
          done
